version: 2
sphinx:
    builder: html
    configuration: docs/conf.py
formats:
    - pdf
    - epub
    - htmlzip
python:
    version: 3.8
    install:
        - requirements: requirements.txt
        - method: pip
    system_packages: true